---
# tasks file for server
- name: Update apt cache
  apt: 
    update_cache: yes 
    cache_valid_time: 3600

- name: Install required software
  apt: name={{ item }} state=present
#  become: yes
  with_items:
    - apache2
    - mysql-server
    - python-mysqldb
    - php7.2-mysql
    - php7.2
    - libapache2-mod-php7.2
    - python-mysqldb
    - php-curl
    - php-gd
    - php-mbstring
    - php-xml
    - php-xmlrpc
    - php-soap
    - php-intl
    - php-zip
